; Flownergy - PlatformIO Configuration
; ESP32 WROOM-32 + PZEM-004T v3.0
;
; PUERTOS:
;   upload_port = COM3  → USB (para flashear el código)
;   monitor_port = COM5 → Bluetooth SPP (para leer datos en producción)
;
; Si no sabes tu COM, buscalo en:
;   Administrador de dispositivos → Puertos (COM y LPT)

[env:esp32dev]
platform   = espressif32
board      = esp32dev
framework  = arduino

; Velocidad del monitor serial
monitor_speed = 115200

; Puerto USB para cargar el firmware (cambia si el tuyo es diferente)
upload_port = COM3

; Partición mínima para que BluetoothSerial compile sin errores
board_build.partitions = min_spiffs.csv

; Dependencias del proyecto
lib_deps =
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    mandulaj/PZEM-004T-v30@^1.1.2

; Flags de compilación opcionales (optimización)
build_flags =
    -DCORE_DEBUG_LEVEL=0
